name: Tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    name: Fullstack CI Tests
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Bun Environment
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Frontend Dependencies, Run Unit Tests & Build UI
        run: |
          cd web
          bun install
          bun run test:unit
          bun run build
        shell: pwsh

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install Python Dependencies
        run: uv sync --all-extras --dev

      - name: Run Pytest (Backend)
        run: uv run pytest -m "not network"
